name: "JS Actions"

on: [push]

jobs:
  action:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1

      - name: "hello-action"
        uses: ./.github/actions/hello-world
        with:
          # first-greeting: "First greet"
          # second-greeting: "Second greet"
          third-greeting: "Third greet only"
